#spring:
#  application:
#    name: consumer-service
#server:
#  port: 8088
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9007/eureka/
#    registry-fetch-interval-seconds: 3
#param: Welcome to Spring Boot
#hystrix:
#  command:
#    default: execution.isolation.thread.timeoutInMilliiseconds
#feign:
#  hystrix:
#    enabled: true
server:
  port: 8088
